### ISSUE TITLE
登录 / 注册时提示验证码错误

### ISSUE THREAD

**Issue by bilibaiWater** [chinosk6/chieri-arcaea-records-frontend#2]
在 https://www.chinosk6.cn/arc/ 注册时提示

> reCaptcha Error
> TypeError: window.grecaptcha.ready is not a function

**Comment by bilibaiWater** [comment]
![image](https://github.com/user-attachments/assets/64d345c6-5d36-4de5-b378-feb6612152fa)
似乎是服务挂了

现在注册/登录都无法进行

**Comment by chinosk6** [comment]
已修复
